### ISSUE TITLE
Output entry formatting

### ISSUE THREAD

**Issue by Sharsie** [mqus/jetbrains-albert-plugin#2]
Hello again @mqus! :)
I wanted to make another PR, but after rebasing on your master branch, my forked repo got totally broken...well, M$ took over, so I'm not really surprised.

However after your last big update it stopped working for me, I dug a little and this is where it starts failing:
https://github.com/mqus/jetbrains-albert-plugin/blob/4a0f662706b38f3512aa7c6cce39e8511d030c26/__init__.py#L159

Replacing it with:
```diff
-                id="%015d" % (now - last_update, project_path, app_name),
+                id="%015d-%s-%s" % (now - last_update, project_path, app_name),
```
Fixes the problem for me at least

The error I was getting:
```
06:45:56 [WARN:python.modulev1] [jetbrains-projects] TypeError: not all arguments converted during string formatting

At:
  /home/becky/.local/share/albert/org.albert.extension.python/modules/jetbrains-projects/__init__.py(164): handleQuery
.
```

**Comment by mqus** [comment]
Thats a dumb mistake from me, sorry. I'll fix it.
