### ISSUE TITLE
`git clone` instruction uses wrong directory (`-` instead of `_`)

### ISSUE THREAD

**Issue by tomsquest** [mqus/jetbrains-albert-plugin#3]
Hi @mqus ,

I don't know if it is intentional, but the install instruction clone the repo under `jetbrains-projects` instead of `jetbrains_projects`, the latter is used in the Albert-Python repo.

![image](https://user-images.githubusercontent.com/365778/104342690-63092400-54fb-11eb-95f0-98f5dba5c897.png)

What do you think, should it be set do `_` or it was a hack to have the two version side by side ?

Thanks,
Tom

**Comment by mqus** [comment]
I didn't really consider the "old" plugin also existing when writing the instructions... I guess I'll update them. For me, the plugins in the python repo get installed by my package manager, so they are in an entirely different place than any plugins I would add manually(like this one)

**Comment by tomsquest** [comment]
Ahh I git-cloned the albert-plugin repo into my $HOME, that's why I got everything in one place.

```
git clone https://github.com/albertlauncher/python.git ~/.local/share/albert/org.albert.extension.python/modules
# then I have jetbrains_project
```

You can close this issue, or I can make a pull request.

**Comment by mqus** [comment]
Did not act on this issue for a while, but right now I think having both co-exist in the same directory is probably for the best. I'll close this issue.
